name: CICD workflow

on:
  push:
    branches: [ main ]

jobs:
  build:
    name : build job
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo & checkout code
        uses: actions/checkout@v2

      - name: Install Node.js  
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 14.x

      - name: Install NPM packages    
        run: npm ci

      - name: Build project  
        run: npm run build

      - name: Run tests  
        run: npm run test

      - name: Upload production-ready build files  
        uses: actions/upload-artifact@v3
        with:
          name: build artifact
          path: ./build

  deploy:
    name : deploy
    needs : build
    runs-on: ubuntu-latest
    steps:
      - name : download artifacts
        uses: actions/download-artifact@v3
        with:
          name: production
          path: ./build
      - name: Deploy to Github pages
        uses: crazy-max/ghaction-github-pages@v2   
        with:
          target_branch: gh-pages
          build_dir: ./build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

      


    


